GitHub_url=https://github.com
CountryPopulation_url=https://worldometers.info/world-population/population-by-country
JavaScriptAlerts_url=https://the-internet.herokuapp.com/javascript_alerts
DynamicContent_url=https://the-internet.herokuapp.com/dynamic_content
Wikipedia_url=https://www.wikipedia.org/
QuotesToScrape_url=https://quotes.toscrape.com/
SauceDemo_url=https://www.saucedemo.com/

browser=chrome

explicitWait=15

implicitWait=15

email=abc1332@gmail.com
password=hjds@123
username=gdsj723
country=India

CancelAlertMessage=You clicked: Cancel

screenshotName=Dummy


validUsername=standard_user
validPassword=secret_sauce
invalidUsername=wrong_user
invalidPassword=wrong_password